name: Scheduled Python Job

on:
  schedule:
    - cron: '0 */2 * * 1-5'  # Runs 2hr once daily between monday to friday

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    env:
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python main.py
